//// FIRST EXERCISE
function javascript_Boot_camp (Teach){

   
   console.log(`This javaScript BootCamp ${Teach} with`);
  
    
}
javascript_Boot_camp ("Teach1");
javascript_Boot_camp ("Teach2");





//// SECOND EXERCISE WEIGHT & HIGHT 
function Health (WEIGHT){
   let S =  18.5 ;
   let N = 18.5 / 24.9 ;
   let O = 25  / 29.9 ;
   let OBESITY =  30/ 35 ;
   

let Health =prompt("Enter Your Weight")
let Hight = prompt("Enter Your Hight")

if (Health > 18.5 &&  Hight <= 150)
{
alert ( "YOU ARE SLIM")
}

if (Health >= 24.9 && Hight <= 160 )
{
   alert("YOUR WEIGHT IS NORMAL");
}


else if ( Health >= 29.9 && Hight <= 170 ){
    alert(" YOU ARE OVERWEIGHT ");
}


else if (Health  >= 35 && Hight <= 180 ){
   alert(" YOU ARE OBESITY");
}


}


////// DONE BY ALGHALIA //////


